version: '3.5'

networks:
  ansible-network:
    name: ansible-network
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  ansible-server:
    image: ubuntu:latest
    container_name: ansible-server
    volumes:
      - .:/app
    networks:
      ansible-network:
        ipv4_address: 192.168.1.2
    command:
      - bash
      - -c
      - |
        apt-get update
        apt-get upgrade -y
        apt-get install sudo
        apt-get install sshpass -y
        apt-get install ansible -y

        cp /app/sudoers /etc -f
        cp /app/ansible.cfg /etc/ansible/ -f
        cp /app/inventory /etc/ansible/
        mv /etc/ansible/inventory /etc/ansible/hosts -f

        sleep infinity

  ansible-node1:
    image: ubuntu:latest
    container_name: ansible-node1
    volumes:
      - .:/app
    networks:
      ansible-network:
        ipv4_address: 192.168.1.3
    command:
      - bash
      - -c
      - |
        apt-get update
        apt-get upgrade -y
        apt-get install sudo
        apt-get install openssh-server -y

        cp /app/sudoers /etc -f
        service ssh start

        sleep infinity

  ansible-node2:
    image: ubuntu:latest
    container_name: ansible-node2
    volumes:
      - .:/app
    networks:
      ansible-network:
        ipv4_address: 192.168.1.4
    command:
      - bash
      - -c
      - |
        apt-get update
        apt-get upgrade -y
        apt-get install sudo
        apt-get install openssh-server -y

        cp /app/sudoers /etc -f
        service ssh start

        sleep infinity