apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-ml-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: netology-ml-app
    spec:
      containers:
        - image: tomcat:8.5.69
          name: netology-ml-container
          ports:
            - containerPort: 8080